### ISSUE TITLE
CTK env value “None” String is not Allowed

### ISSUE THREAD

**Issue by dragon1990** [mosip/mosip-compliance-toolkit-ui#549]
![image](https://github.com/mosip/mosip-compliance-toolkit-ui/assets/12669381/0f003d1b-deec-4b12-8f6f-f443339fc9d3)
in the MDS deviceinfo document, it says
for devices that are not registered the environment is “None”.
I set the env filed with “None” String for the not registered device, but the CTK Tested failed。

I looked into the ctk code file 【DeviceInfoNotRegisteredResponseSchema.json】
it only allow values are “Staging”, “Developer”, “Pre-Production” or “Production”
just as the image below shows

![image](https://github.com/mosip/mosip-compliance-toolkit-ui/assets/12669381/1570d020-d288-4bef-ba55-c325c7f5d3f0)

**Comment by mayuradesh** [comment]
Hi

Thanks for posting the query.

I think you are referring to `DeviceInfoNotRegisteredResponseSchema.json` in master branch.
The "None" option is available in our release-1.x.x branch.

Do check the release-1.x.x branch. I will get the master branch updated too.

Regards
