### ISSUE TITLE
Whether deviceInfo::digitalId need to Base64 Encoded for not registered device(L1 Device)

### ISSUE THREAD

**Issue by dragon1990** [mosip/mosip-compliance-toolkit-ui#550]
https://community.mosip.io/t/whether-deviceinfo-digitalid-need-to-base64-encoded-for-not-registered-device-l1-device/764

![image](https://github.com/mosip/mosip-compliance-toolkit-ui/assets/12669381/9d8be167-502c-4ade-ba76-3e4435bb4ebe)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by mayuradesh** [comment]
Hi

The issue reported in MOSIP community has been addressed in "develop" branch and in our upcoming "release 1.3.0" as well.
The fix is not available in "release-1.2.0". 

Hope this helps.

~ Mayura
