### ISSUE TITLE
Android SBI CTK Check Device Status failed: SBI1028, SBI1029.

### ISSUE THREAD

**Issue by hoanghiep23** [mosip/mosip-compliance-toolkit-ui#644]
CTK Android test SBI1028, SBI1029 failed with error "Unable to connect to device / SBI".
After checking I see that:
    - sbi-testcase-android-service.ts: 
         + callSBIMethodAndroid: always request SBI_METHOD_DISCOVER before other request method (SBI_METHOD_DEVICE_INFO, SBI_METHOD_RCAPTURE, SBI_METHOD_CAPTURE)
    - If device status is Not Ready or Not Registered, SBI discovery response will contains error, such as: 
       {
           "deviceStatus": "Not Ready",
            "error": {
                 "errorCode": "106",
                 "errorInfo": "Device not found"
             }
      }
    - MosipSbiCapacitorPlugin.onDiscoverResult: if discovery response contains errorCode != 0, this will return status = failure.
      This will cause sbi-testcase-android-service.ts:callSBIMethodAndroid does not receive response and will end with error "Unable to connect to device / SBI".
Please help me to check and correct this test case.
Thank you.
    
![Screenshot_20231219-144109_mosip-compliance-toolkit-uiy](https://github.com/mosip/mosip-compliance-toolkit-ui/assets/1152308/a35c065c-fd18-4443-a439-30752a5a32ce)

**Comment by hoanghiep23** [comment]
@mayuradesh Please help me to check this test case.

**Comment by mayuradesh** [comment]
I will get back to you on this

**Comment by mayuradesh** [comment]
Hi 

Have a look at MDS specs https://docs.mosip.io/1.1.5/biometrics/mosip-device-service-specification

Device Discovery response should be as below even for "Not Ready" or "Not Registered" devices,
<img width="479" alt="image" src="https://github.com/mosip/mosip-compliance-toolkit-ui/assets/52281514/6d482378-5083-43e3-81d7-cee4be354465">

There should be **NO error in Device Discovery response**, even for "Not Ready" or "Not Registered" devices. Error is possible for parsing issue etc.

The error codes that you have mentioned is for **Device Info Response**.
<img width="475" alt="image" src="https://github.com/mosip/mosip-compliance-toolkit-ui/assets/52281514/1bf96caf-cb67-47bb-b3b3-93df92882cc3">

If you correct your implementation, then Discover will proceed correctly and you will be able to execute the testcases SBI1028 and SBI1029.

Hope this helps.
~ Mayura

**Comment by hoanghiep23** [comment]
Hi,
If there is no error in Device discovery response, I can pass the testcases SBI1028 and SBI1029. 
The MDS specs should be updated, currently it requires error codes should be sent for device in "Busy", "Not Ready" and "Not Registered" for Device Discovery Response.
![Screenshot 2023-12-27 160654_](https://github.com/mosip/mosip-compliance-toolkit-ui/assets/1152308/d1599b79-3450-4f99-97e9-e6d56486d296)
Thank you.

**Comment by mayuradesh** [comment]
Hi

I take your point. As per specs, even Discover can have an error for these statuses.

So I will update our code which is doing Discover before every method call. It is redundant and cause an issue in this case. Updated code will be in "develop" branch and upcoming release too.

Thanks
